apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rest-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-kit-example-rest-api-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
